#pragma once
// win
#include <Windows.h>
#include <winternl.h>
#include <Xinput.h>
#include <comdef.h>
#include <minwindef.h>
#include <winbase.h>
#include <intrin.h>
#include <psapi.h>

// stl
#include <vector>
#include <memory>
#include <string>
#include <iostream>
#include <fstream>
#include <cctype>
#include <clocale>
#include <algorithm>
#include <sstream>
// game
#include "sdk\vector.h"
#include "sdk\characterbody.h"
#include "sdk\enemy.h"
#include "sdk\maphandler.h"
#include "sdk\player.h"
#include "sdk\game.h"

// cheat
#include "interfaces.h"
#include "game.h"
#include "hooks.h"
